// extensions/simple-blog/src/web/pages/console/article/add.tsx
import { useDocumentHead } from "@buildingai/hooks";
import { Button } from "@buildingai/ui/components/ui/button";
import { ArrowLeft } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";

import { useCreateArticleMutation } from "../../../services";
import type { CreateArticleParams, UpdateArticleParams } from "../../../services/types/article";
import ArticleForm from "./components/form";

export default function ArticleAddPage() {
    useDocumentHead({
        title: "发布文章",
    });

    const navigate = useNavigate();
    const createMutation = useCreateArticleMutation();

    const handleSubmit = async (data: CreateArticleParams | UpdateArticleParams) => {
        try {
            await createMutation.mutateAsync(data as CreateArticleParams);
            toast.success("创建成功");
            setTimeout(() => navigate(-1), 1000);
        } catch (error) {
            console.error(error);
        }
    };

    const handleCancel = () => {
        navigate(-1);
    };

    return (
        <>
            <div className="bg-background sticky top-0 z-10 mb-4 flex w-full items-center justify-baseline pb-2">
                <Button variant="secondary" size="icon" onClick={() => navigate(-1)}>
                    <ArrowLeft />
                </Button>

                <h1 className="ml-4 text-xl font-bold">发布文章</h1>
            </div>

            <ArticleForm
                onSubmit={handleSubmit}
                onCancel={handleCancel}
                isSubmitting={createMutation.isPending}
            />
        </>
    );
}

// extensions/simple-blog/src/web-vue/pages/console/article/add.vue
<script setup lang="ts">
/**
 * 发布文章页
 * @description 创建新文章
 */
import { useRouter } from "vue-router";
import { useCreateArticle } from "../../../composables/useArticle";
import type { CreateArticleParams } from "../../../composables/useArticle";
import ArticleForm from "./components/form.vue";

const router = useRouter();
const createMutation = useCreateArticle();

const handleSubmit = async (data: CreateArticleParams) => {
    try {
        await createMutation.submit(data);
        alert("创建成功");
        setTimeout(() => router.back(), 1000);
    } catch (error) {
        console.error(error);
    }
};

const handleCancel = () => {
    router.back();
};
</script>

<template>
    <div class="p-4">
        <div class="sticky top-0 z-10 mb-4 flex w-full items-center bg-background pb-2">
            <button class="btn btn-secondary btn-icon" @click="router.back()">
                <!-- ArrowLeft SVG -->
                <svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="m12 19-7-7 7-7"/>
                    <path d="M19 12H5"/>
                </svg>
            </button>
            <h1 class="ml-4 text-xl font-bold">发布文章</h1>
        </div>

        <ArticleForm
            @submit="handleSubmit"
            @cancel="handleCancel"
            :is-submitting="createMutation.isSubmitting.value"
        />
    </div>
</template>
